# Generated by Django 2.1.5 on 2019-02-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20190216_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailuser',
            name='Specialization',
            field=models.CharField(blank=True, choices=[('Pathologist', 'PATHOLOGIST'), ('Radiologist', 'RADIOLOGIST'), ('Obstetrician', 'OBSTETRICIAN'), ('Cardiologist', 'CARDIOLOGIST'), ('Endocrinologist', 'ENDOCRINOLOGIST'), ('', '---------')], max_length=25, null=True),
        ),
    ]
